// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public enum NodeType: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case building = 0
  case room = 1
  case hallway = 2
  case entrance = 3
  case stairs = 4
  case elevator = 5
  case cafearea = 6
  case studyspace = 7
  case outdoorpath = 8

  public static var max: NodeType { return .outdoorpath }
  public static var min: NodeType { return .building }
}


public struct Coordinates: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_1_24() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case x = 4
    case y = 6
    case z = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var x: Float32 { let o = _accessor.offset(VTOFFSET.x.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Float32.self, at: o) }
  public var y: Float32 { let o = _accessor.offset(VTOFFSET.y.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Float32.self, at: o) }
  public var z: Float32 { let o = _accessor.offset(VTOFFSET.z.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Float32.self, at: o) }
  public static func startCoordinates(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 3) }
  public static func add(x: Float32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: x, def: 0.0, at: VTOFFSET.x.p) }
  public static func add(y: Float32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: y, def: 0.0, at: VTOFFSET.y.p) }
  public static func add(z: Float32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: z, def: 0.0, at: VTOFFSET.z.p) }
  public static func endCoordinates(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createCoordinates(
    _ fbb: inout FlatBufferBuilder,
    x: Float32 = 0.0,
    y: Float32 = 0.0,
    z: Float32 = 0.0
  ) -> Offset {
    let __start = Coordinates.startCoordinates(&fbb)
    Coordinates.add(x: x, &fbb)
    Coordinates.add(y: y, &fbb)
    Coordinates.add(z: z, &fbb)
    return Coordinates.endCoordinates(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.x.p, fieldName: "x", required: false, type: Float32.self)
    try _v.visit(field: VTOFFSET.y.p, fieldName: "y", required: false, type: Float32.self)
    try _v.visit(field: VTOFFSET.z.p, fieldName: "z", required: false, type: Float32.self)
    _v.finish()
  }
}

public struct NodeAttributes: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_1_24() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case wheelchairAccessible = 4
    case capacity = 6
    case indoor = 8
    case restrictedAccess = 10
    case arAnchorId = 12
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var wheelchairAccessible: Bool { let o = _accessor.offset(VTOFFSET.wheelchairAccessible.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var capacity: Int32 { let o = _accessor.offset(VTOFFSET.capacity.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var indoor: Bool { let o = _accessor.offset(VTOFFSET.indoor.v); return o == 0 ? true : _accessor.readBuffer(of: Bool.self, at: o) }
  public var restrictedAccess: Bool { let o = _accessor.offset(VTOFFSET.restrictedAccess.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var arAnchorId: String? { let o = _accessor.offset(VTOFFSET.arAnchorId.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var arAnchorIdSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.arAnchorId.v) }
  public static func startNodeAttributes(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 5) }
  public static func add(wheelchairAccessible: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: wheelchairAccessible, def: false,
   at: VTOFFSET.wheelchairAccessible.p) }
  public static func add(capacity: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: capacity, def: 0, at: VTOFFSET.capacity.p) }
  public static func add(indoor: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: indoor, def: true,
   at: VTOFFSET.indoor.p) }
  public static func add(restrictedAccess: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: restrictedAccess, def: false,
   at: VTOFFSET.restrictedAccess.p) }
  public static func add(arAnchorId: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: arAnchorId, at: VTOFFSET.arAnchorId.p) }
  public static func endNodeAttributes(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createNodeAttributes(
    _ fbb: inout FlatBufferBuilder,
    wheelchairAccessible: Bool = false,
    capacity: Int32 = 0,
    indoor: Bool = true,
    restrictedAccess: Bool = false,
    arAnchorIdOffset arAnchorId: Offset = Offset()
  ) -> Offset {
    let __start = NodeAttributes.startNodeAttributes(&fbb)
    NodeAttributes.add(wheelchairAccessible: wheelchairAccessible, &fbb)
    NodeAttributes.add(capacity: capacity, &fbb)
    NodeAttributes.add(indoor: indoor, &fbb)
    NodeAttributes.add(restrictedAccess: restrictedAccess, &fbb)
    NodeAttributes.add(arAnchorId: arAnchorId, &fbb)
    return NodeAttributes.endNodeAttributes(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.wheelchairAccessible.p, fieldName: "wheelchairAccessible", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.capacity.p, fieldName: "capacity", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.indoor.p, fieldName: "indoor", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.restrictedAccess.p, fieldName: "restrictedAccess", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.arAnchorId.p, fieldName: "arAnchorId", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct Node: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_1_24() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case id = 4
    case name = 6
    case type = 8
    case coordinates = 10
    case floor = 12
    case attributes = 14
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var id: String! { let o = _accessor.offset(VTOFFSET.id.v); return _accessor.string(at: o) }
  public var idSegmentArray: [UInt8]! { return _accessor.getVector(at: VTOFFSET.id.v) }
  public var name: String? { let o = _accessor.offset(VTOFFSET.name.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var nameSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.name.v) }
  public var type: NodeType { let o = _accessor.offset(VTOFFSET.type.v); return o == 0 ? .building : NodeType(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .building }
  public var coordinates: Coordinates? { let o = _accessor.offset(VTOFFSET.coordinates.v); return o == 0 ? nil : Coordinates(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public var floor: Int32 { let o = _accessor.offset(VTOFFSET.floor.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var attributes: NodeAttributes? { let o = _accessor.offset(VTOFFSET.attributes.v); return o == 0 ? nil : NodeAttributes(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startNode(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 6) }
  public static func add(id: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: id, at: VTOFFSET.id.p) }
  public static func add(name: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: name, at: VTOFFSET.name.p) }
  public static func add(type: NodeType, _ fbb: inout FlatBufferBuilder) { fbb.add(element: type.rawValue, def: 0, at: VTOFFSET.type.p) }
  public static func add(coordinates: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: coordinates, at: VTOFFSET.coordinates.p) }
  public static func add(floor: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: floor, def: 0, at: VTOFFSET.floor.p) }
  public static func add(attributes: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: attributes, at: VTOFFSET.attributes.p) }
  public static func endNode(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); fbb.require(table: end, fields: [4]); return end }
  public static func createNode(
    _ fbb: inout FlatBufferBuilder,
    idOffset id: Offset,
    nameOffset name: Offset = Offset(),
    type: NodeType = .building,
    coordinatesOffset coordinates: Offset = Offset(),
    floor: Int32 = 0,
    attributesOffset attributes: Offset = Offset()
  ) -> Offset {
    let __start = Node.startNode(&fbb)
    Node.add(id: id, &fbb)
    Node.add(name: name, &fbb)
    Node.add(type: type, &fbb)
    Node.add(coordinates: coordinates, &fbb)
    Node.add(floor: floor, &fbb)
    Node.add(attributes: attributes, &fbb)
    return Node.endNode(&fbb, start: __start)
  }
  public static func sortVectorOfNode(offsets:[Offset], _ fbb: inout FlatBufferBuilder) -> Offset {
    var off = offsets
    off.sort { Table.compare(Table.offset(Int32($1.o), vOffset: 4, fbb: fbb.buffer), Table.offset(Int32($0.o), vOffset: 4, fbb: fbb.buffer), fbb: fbb.buffer) < 0 } 
    return fbb.createVector(ofOffsets: off)
  }
  fileprivate static func lookupByKey(vector: Int32, key: String, fbb: ByteBuffer) -> Node? {
    let key = key.utf8.map { $0 }
    var span = fbb.read(def: Int32.self, position: Int(vector - 4))
    var start: Int32 = 0
    while span != 0 {
      var middle = span / 2
      let tableOffset = Table.indirect(vector + 4 * (start + middle), fbb)
      let comp = Table.compare(Table.offset(Int32(fbb.capacity) - tableOffset, vOffset: 4, fbb: fbb), key, fbb: fbb)
      if comp > 0 {
        span = middle
      } else if comp < 0 {
        middle += 1
        start += middle
        span -= middle
      } else {
        return Node(fbb, o: tableOffset)
      }
    }
    return nil
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.id.p, fieldName: "id", required: true, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.name.p, fieldName: "name", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.type.p, fieldName: "type", required: false, type: NodeType.self)
    try _v.visit(field: VTOFFSET.coordinates.p, fieldName: "coordinates", required: false, type: ForwardOffset<Coordinates>.self)
    try _v.visit(field: VTOFFSET.floor.p, fieldName: "floor", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.attributes.p, fieldName: "attributes", required: false, type: ForwardOffset<NodeAttributes>.self)
    _v.finish()
  }
}

public struct EdgeAttributes: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_1_24() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case indoor = 4
    case stairsCount = 6
    case crowdedDuringPeaks = 8
    case wheelchairAccessible = 10
    case covered = 12
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var indoor: Bool { let o = _accessor.offset(VTOFFSET.indoor.v); return o == 0 ? true : _accessor.readBuffer(of: Bool.self, at: o) }
  public var stairsCount: Int32 { let o = _accessor.offset(VTOFFSET.stairsCount.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var crowdedDuringPeaks: Bool { let o = _accessor.offset(VTOFFSET.crowdedDuringPeaks.v); return o == 0 ? false : _accessor.readBuffer(of: Bool.self, at: o) }
  public var wheelchairAccessible: Bool { let o = _accessor.offset(VTOFFSET.wheelchairAccessible.v); return o == 0 ? true : _accessor.readBuffer(of: Bool.self, at: o) }
  public var covered: Bool { let o = _accessor.offset(VTOFFSET.covered.v); return o == 0 ? true : _accessor.readBuffer(of: Bool.self, at: o) }
  public static func startEdgeAttributes(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 5) }
  public static func add(indoor: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: indoor, def: true,
   at: VTOFFSET.indoor.p) }
  public static func add(stairsCount: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: stairsCount, def: 0, at: VTOFFSET.stairsCount.p) }
  public static func add(crowdedDuringPeaks: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: crowdedDuringPeaks, def: false,
   at: VTOFFSET.crowdedDuringPeaks.p) }
  public static func add(wheelchairAccessible: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: wheelchairAccessible, def: true,
   at: VTOFFSET.wheelchairAccessible.p) }
  public static func add(covered: Bool, _ fbb: inout FlatBufferBuilder) { fbb.add(element: covered, def: true,
   at: VTOFFSET.covered.p) }
  public static func endEdgeAttributes(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createEdgeAttributes(
    _ fbb: inout FlatBufferBuilder,
    indoor: Bool = true,
    stairsCount: Int32 = 0,
    crowdedDuringPeaks: Bool = false,
    wheelchairAccessible: Bool = true,
    covered: Bool = true
  ) -> Offset {
    let __start = EdgeAttributes.startEdgeAttributes(&fbb)
    EdgeAttributes.add(indoor: indoor, &fbb)
    EdgeAttributes.add(stairsCount: stairsCount, &fbb)
    EdgeAttributes.add(crowdedDuringPeaks: crowdedDuringPeaks, &fbb)
    EdgeAttributes.add(wheelchairAccessible: wheelchairAccessible, &fbb)
    EdgeAttributes.add(covered: covered, &fbb)
    return EdgeAttributes.endEdgeAttributes(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.indoor.p, fieldName: "indoor", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.stairsCount.p, fieldName: "stairsCount", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.crowdedDuringPeaks.p, fieldName: "crowdedDuringPeaks", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.wheelchairAccessible.p, fieldName: "wheelchairAccessible", required: false, type: Bool.self)
    try _v.visit(field: VTOFFSET.covered.p, fieldName: "covered", required: false, type: Bool.self)
    _v.finish()
  }
}

public struct Edge: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_1_24() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case sourceId = 4
    case targetId = 6
    case distance = 8
    case avgTime = 10
    case attributes = 12
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var sourceId: String? { let o = _accessor.offset(VTOFFSET.sourceId.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var sourceIdSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.sourceId.v) }
  public var targetId: String? { let o = _accessor.offset(VTOFFSET.targetId.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var targetIdSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.targetId.v) }
  public var distance: Float32 { let o = _accessor.offset(VTOFFSET.distance.v); return o == 0 ? 0.0 : _accessor.readBuffer(of: Float32.self, at: o) }
  public var avgTime: Int32 { let o = _accessor.offset(VTOFFSET.avgTime.v); return o == 0 ? 0 : _accessor.readBuffer(of: Int32.self, at: o) }
  public var attributes: EdgeAttributes? { let o = _accessor.offset(VTOFFSET.attributes.v); return o == 0 ? nil : EdgeAttributes(_accessor.bb, o: _accessor.indirect(o + _accessor.position)) }
  public static func startEdge(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 5) }
  public static func add(sourceId: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: sourceId, at: VTOFFSET.sourceId.p) }
  public static func add(targetId: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: targetId, at: VTOFFSET.targetId.p) }
  public static func add(distance: Float32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: distance, def: 0.0, at: VTOFFSET.distance.p) }
  public static func add(avgTime: Int32, _ fbb: inout FlatBufferBuilder) { fbb.add(element: avgTime, def: 0, at: VTOFFSET.avgTime.p) }
  public static func add(attributes: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: attributes, at: VTOFFSET.attributes.p) }
  public static func endEdge(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createEdge(
    _ fbb: inout FlatBufferBuilder,
    sourceIdOffset sourceId: Offset = Offset(),
    targetIdOffset targetId: Offset = Offset(),
    distance: Float32 = 0.0,
    avgTime: Int32 = 0,
    attributesOffset attributes: Offset = Offset()
  ) -> Offset {
    let __start = Edge.startEdge(&fbb)
    Edge.add(sourceId: sourceId, &fbb)
    Edge.add(targetId: targetId, &fbb)
    Edge.add(distance: distance, &fbb)
    Edge.add(avgTime: avgTime, &fbb)
    Edge.add(attributes: attributes, &fbb)
    return Edge.endEdge(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.sourceId.p, fieldName: "sourceId", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.targetId.p, fieldName: "targetId", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.distance.p, fieldName: "distance", required: false, type: Float32.self)
    try _v.visit(field: VTOFFSET.avgTime.p, fieldName: "avgTime", required: false, type: Int32.self)
    try _v.visit(field: VTOFFSET.attributes.p, fieldName: "attributes", required: false, type: ForwardOffset<EdgeAttributes>.self)
    _v.finish()
  }
}

public struct CampusMap: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_25_1_24() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case name = 4
    case nodes = 6
    case edges = 8
    case version = 10
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var name: String? { let o = _accessor.offset(VTOFFSET.name.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var nameSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.name.v) }
  public var hasNodes: Bool { let o = _accessor.offset(VTOFFSET.nodes.v); return o == 0 ? false : true }
  public var nodesCount: Int32 { let o = _accessor.offset(VTOFFSET.nodes.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func nodes(at index: Int32) -> Node? { let o = _accessor.offset(VTOFFSET.nodes.v); return o == 0 ? nil : Node(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public func nodesBy(key: String) -> Node? { let o = _accessor.offset(VTOFFSET.nodes.v); return o == 0 ? nil : Node.lookupByKey(vector: _accessor.vector(at: o), key: key, fbb: _accessor.bb) }
  public var hasEdges: Bool { let o = _accessor.offset(VTOFFSET.edges.v); return o == 0 ? false : true }
  public var edgesCount: Int32 { let o = _accessor.offset(VTOFFSET.edges.v); return o == 0 ? 0 : _accessor.vector(count: o) }
  public func edges(at index: Int32) -> Edge? { let o = _accessor.offset(VTOFFSET.edges.v); return o == 0 ? nil : Edge(_accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4)) }
  public var version: String? { let o = _accessor.offset(VTOFFSET.version.v); return o == 0 ? nil : _accessor.string(at: o) }
  public var versionSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.version.v) }
  public static func startCampusMap(_ fbb: inout FlatBufferBuilder) -> UOffset { fbb.startTable(with: 4) }
  public static func add(name: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: name, at: VTOFFSET.name.p) }
  public static func addVectorOf(nodes: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: nodes, at: VTOFFSET.nodes.p) }
  public static func addVectorOf(edges: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: edges, at: VTOFFSET.edges.p) }
  public static func add(version: Offset, _ fbb: inout FlatBufferBuilder) { fbb.add(offset: version, at: VTOFFSET.version.p) }
  public static func endCampusMap(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset { let end = Offset(offset: fbb.endTable(at: start)); return end }
  public static func createCampusMap(
    _ fbb: inout FlatBufferBuilder,
    nameOffset name: Offset = Offset(),
    nodesVectorOffset nodes: Offset = Offset(),
    edgesVectorOffset edges: Offset = Offset(),
    versionOffset version: Offset = Offset()
  ) -> Offset {
    let __start = CampusMap.startCampusMap(&fbb)
    CampusMap.add(name: name, &fbb)
    CampusMap.addVectorOf(nodes: nodes, &fbb)
    CampusMap.addVectorOf(edges: edges, &fbb)
    CampusMap.add(version: version, &fbb)
    return CampusMap.endCampusMap(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.name.p, fieldName: "name", required: false, type: ForwardOffset<String>.self)
    try _v.visit(field: VTOFFSET.nodes.p, fieldName: "nodes", required: false, type: ForwardOffset<Vector<ForwardOffset<Node>, Node>>.self)
    try _v.visit(field: VTOFFSET.edges.p, fieldName: "edges", required: false, type: ForwardOffset<Vector<ForwardOffset<Edge>, Edge>>.self)
    try _v.visit(field: VTOFFSET.version.p, fieldName: "version", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

